import { useState } from "react";
import { Modal, Button, Input, message, Typography, Space, Alert } from "antd";
import apiClient from "../api/client";

const { Text, Paragraph } = Typography;

interface TwoFAModalProps {
  open: boolean;
  totpEnabled: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export default function TwoFAModal({ open, totpEnabled, onClose, onSuccess }: TwoFAModalProps) {
  const [loading, setLoading] = useState(false);
  const [enrollData, setEnrollData] = useState<{ secret: string; provisioning_uri: string } | null>(null);
  const [code, setCode] = useState("");
  const [verifying, setVerifying] = useState(false);

  const startEnroll = async () => {
    setLoading(true);
    try {
      const { data } = await apiClient.post("/auth/2fa/enroll");
      setEnrollData(data);
    } catch (e: any) {
      message.error(e?.response?.data?.detail || "Failed to start 2FA enrollment");
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async () => {
    if (!code.trim() || code.length !== 6) {
      message.warning("Please enter a valid 6-digit code");
      return;
    }
    setVerifying(true);
    try {
      await apiClient.post("/auth/2fa/verify", { code: code.trim() });
      message.success("2FA enabled successfully!");
      setEnrollData(null);
      setCode("");
      onSuccess();
      onClose();
    } catch (e: any) {
      message.error(e?.response?.data?.detail || "Verification failed");
    } finally {
      setVerifying(false);
    }
  };

  return (
    <Modal
      title="Two-Factor Authentication (2FA)"
      open={open}
      footer={null}
      onCancel={() => {
        setEnrollData(null);
        setCode("");
        onClose();
      }}
      destroyOnClose
    >
      <div style={{ padding: "12px 0" }}>
        {totpEnabled ? (
          <Space direction="vertical" style={{ width: "100%" }}>
            <Alert
              message="2FA is Enabled"
              description="Your account is secured with two-factor authentication (TOTP)."
              type="success"
              showIcon
            />
            <Paragraph style={{ marginTop: 12 }}>
              To disable or reset 2FA, please contact your platform administrator.
            </Paragraph>
          </Space>
        ) : !enrollData ? (
          <Space direction="vertical" style={{ width: "100%" }}>
            <Paragraph>
              Two-factor authentication adds an extra layer of security to your account by requiring a temporary verification code in addition to your password.
            </Paragraph>
            <Button type="primary" onClick={startEnroll} loading={loading}>
              Set up 2FA
            </Button>
          </Space>
        ) : (
          <Space direction="vertical" align="center" style={{ width: "100%", textAlign: "center" }}>
            <Paragraph style={{ textAlign: "left" }}>
              1. Scan the QR code below using your authenticator app (Google Authenticator, Duo, Authy, etc.):
            </Paragraph>
            <div style={{ padding: 12, background: "#fff", borderRadius: 8, display: "inline-block" }}>
              <img
                src={`https://chart.googleapis.com/chart?cht=qr&chs=200x200&chl=${encodeURIComponent(enrollData.provisioning_uri)}`}
                alt="2FA QR Code"
                style={{ display: "block" }}
              />
            </div>
            <Paragraph style={{ textAlign: "left", marginTop: 8 }}>
              Or enter this code manually: <br />
              <Text code copyable>{enrollData.secret}</Text>
            </Paragraph>
            <Paragraph style={{ textAlign: "left" }}>
              2. Enter the 6-digit verification code generated by your app:
            </Paragraph>
            <Input
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
              placeholder="000000"
              style={{ width: 160, fontSize: 18, textAlign: "center", letterSpacing: 4 }}
              maxLength={6}
            />
            <Button
              type="primary"
              onClick={handleVerify}
              loading={verifying}
              style={{ marginTop: 12 }}
            >
              Verify & Activate
            </Button>
          </Space>
        )}
      </div>
    </Modal>
  );
}
