"""make_customer_id_nullable_and_add_lead_company_name

Revision ID: e05ca1310c63
Revises: 1e336676eeac
Create Date: 2026-07-01 16:55:50.682043

"""
from alembic import op
import sqlalchemy as sa


revision = 'e05ca1310c63'
down_revision = '1e336676eeac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.alter_column('quotations', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('leads', 'company_name')
    # ### end Alembic commands ###
